dependencies:
	sudo apt install python3 python3-dev python3-virtualenv nodejs npm

node:
	cd project/{{ projectname }}/layout; npm install

cashtable:
	 docker-compose exec wsgi ../bin/python manage.py createcachetable 

init:
	sudo ./init.py
	chown $$USER . -R
	service nginx reload

install: dependencies init node up update cashtable theme

up:
	docker-compose up -d --scale wsgi={{ scale }}
	{% if not development %}
	chown www-data:www-data static -R
	chown www-data:www-data media -R
	{% endif %}

down:
	docker-compose down

recreate: down up

restart:
	docker-compose restart

reload:
	touch project/{{ projectname }}/{{ projectname }}/settings.py

clearcache:
	docker-compose exec redis redis-cli FLUSHALL

chown:
	chown www-data:www-data static -R
	chown www-data:www-data media -R

migrations:
	docker-compose exec wsgi ../bin/python manage.py makemigrations

migrate:
	docker-compose exec wsgi ../bin/python manage.py migrate

messages:
	{% if  development %}
	docker-compose exec wsgi ../bin/python manage.py  makeallmessages -a -i node_modules
	{% endif %}
	docker-compose exec wsgi ../bin/python manage.py compilemessages

{% if  development %}
theme: node
	cd project/{{ projectname }}/layout; npm run dev
	docker-compose exec wsgi ../bin/python manage.py collectstatic --noinput -l -i */report.html
	cd project/{{ projectname }}/layout; npm run watch

fixtures:
	docker-compose exec wsgi ../bin/python manage.py loaddata initial_data

update: pull migrate fixtures messages theme 
{% else %}
theme: node
	cd project/{{ projectname }}/layout; npm run build
	docker-compose exec wsgi ../bin/python manage.py collectstatic --noinput

fixtures:
	echo "Skipping fixtures in production"

update: pull migrate fixtures messages theme chown clearcache restart 
{% endif %}

pull:
	cd project/{{ projectname }}; git pull

update: pull migrate fixtures messages theme reload clearcache

logs:
	docker-compose logs -f --timestamp --tail 100
